name: Build Docker Image for API Gateway

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    environment: ${{ github.ref_name }}  # Selecciona el environment basado en la rama

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20

      - name: Build the Docker image
        run: |
          docker build -t my-api-gateway:latest .
