name: Build Docker Image for API Gateway

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'develop' }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20

      - name: Build the Docker image
        run: |
          docker build -t tastes-api-gateway:latest .
      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 340544373363.dkr.ecr.us-west-1.amazonaws.com
      - name: Tag Docker image for ECR
        run: |
          docker tag tastes-api-gateway:latest 340544373363.dkr.ecr.us-west-1.amazonaws.com/tastes-api-gateway
      - name: Push Docker image to ECR
        run: |
          docker push 340544373363.dkr.ecr.us-west-1.amazonaws.com/tastes-api-gateway
